/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_ActionTable */

#ifndef _Included_com_mascotcapsule_micro3d_v3_ActionTable
#define _Included_com_mascotcapsule_micro3d_v3_ActionTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_ActionTable
 * Method:    nInit
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_ActionTable_nInit
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_ActionTable
 * Method:    nGetNumActions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_ActionTable_nGetNumActions
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_ActionTable
 * Method:    nGetNumFrames
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_ActionTable_nGetNumFrames
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_ActionTable
 * Method:    nFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_ActionTable_nFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_ActionTable
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_ActionTable_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
