/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Vector3D */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Vector3D
#define _Included_com_mascotcapsule_micro3d_v3_Vector3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    unit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_unit
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    nCross
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_nCross
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    nDot
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_nDot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    nCross2
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_nCross2
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    nDot2
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_nDot2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Vector3D
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Vector3D_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
