/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Graphics3D */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Graphics3D
#define _Included_com_mascotcapsule_micro3d_v3_Graphics3D
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_LIST_VERSION_1_0
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_LIST_VERSION_1_0 -33554431L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_END
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_END -2147483648L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_NOP
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_NOP -2130706432L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_FLUSH
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_FLUSH -2113929216L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_ATTRIBUTE
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_ATTRIBUTE -2097152000L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_CLIP
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_CLIP -2080374784L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_CENTER
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_CENTER -2063597568L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_TEXTURE_INDEX
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_TEXTURE_INDEX -2046820352L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_AFFINE_INDEX
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_AFFINE_INDEX -2030043136L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PARALLEL_SCALE
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PARALLEL_SCALE -1879048192L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PARALLEL_SIZE
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PARALLEL_SIZE -1862270976L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PERSPECTIVE_FOV
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PERSPECTIVE_FOV -1845493760L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PERSPECTIVE_WH
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_PERSPECTIVE_WH -1828716544L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_AMBIENT_LIGHT
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_AMBIENT_LIGHT -1610612736L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_DIRECTION_LIGHT
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_DIRECTION_LIGHT -1593835520L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_THRESHOLD
#define com_mascotcapsule_micro3d_v3_Graphics3D_COMMAND_THRESHOLD -1358954496L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_POINTS
#define com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_POINTS 16777216L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_LINES
#define com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_LINES 33554432L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_TRIANGLES
#define com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_TRIANGLES 50331648L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_QUADS
#define com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_QUADS 67108864L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_POINT_SPRITES
#define com_mascotcapsule_micro3d_v3_Graphics3D_PRIMITVE_POINT_SPRITES 83886080L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_LOCAL_SIZE
#define com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_LOCAL_SIZE 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_PIXEL_SIZE
#define com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_PIXEL_SIZE 1L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_PERSPECTIVE
#define com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_PERSPECTIVE 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_NO_PERS
#define com_mascotcapsule_micro3d_v3_Graphics3D_POINT_SPRITE_NO_PERS 2L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_LIGHTING
#define com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_LIGHTING 1L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_SPHERE_MAP
#define com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_SPHERE_MAP 2L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_TOON_SHADING
#define com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_TOON_SHADING 4L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_SEMI_TRANSPARENT
#define com_mascotcapsule_micro3d_v3_Graphics3D_ENV_ATTR_SEMI_TRANSPARENT 8L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_LIGHTING
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_LIGHTING 1L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_SPHERE_MAP
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_SPHERE_MAP 2L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_COLORKEY
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_COLORKEY 16L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_NORMAL
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_NORMAL 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_HALF
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_HALF 32L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_ADD
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_ADD 64L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_SUB
#define com_mascotcapsule_micro3d_v3_Graphics3D_PATTR_BLEND_SUB 96L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_NONE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_NONE 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_PER_FACE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_PER_FACE 512L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_PER_VERTEX
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_NORMAL_PER_VERTEX 768L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_NONE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_NONE 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_PER_COMMAND
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_PER_COMMAND 1024L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_PER_FACE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_COLOR_PER_FACE 2048L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_TEXURE_COORD_NONE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_TEXURE_COORD_NONE 0L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_CMD
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_CMD 4096L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_FACE
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_FACE 8192L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_VERTEX
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_POINT_SPRITE_PARAMS_PER_VERTEX 12288L
#undef com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_TEXURE_COORD
#define com_mascotcapsule_micro3d_v3_Graphics3D_PDATA_TEXURE_COORD 12288L
/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nInit
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nBind
 * Signature: ([IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nBind
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nCapture
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nCapture
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nRender
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nRender
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nDrawCmd
 * Signature: ([Lcom/mascotcapsule/micro3d/v3/Texture;IILcom/mascotcapsule/micro3d/v3/FigureLayout;Lcom/mascotcapsule/micro3d/v3/Effect3D;[I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nDrawCmd
  (JNIEnv *, jobject, jobjectArray, jint, jint, jobject, jobject, jintArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nDrawFigure
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Figure;IILcom/mascotcapsule/micro3d/v3/FigureLayout;Lcom/mascotcapsule/micro3d/v3/Effect3D;)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nDrawFigure
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nRenderPrimitive
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Texture;IILcom/mascotcapsule/micro3d/v3/FigureLayout;Lcom/mascotcapsule/micro3d/v3/Effect3D;I[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nRenderPrimitive
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jint, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nRenderFigure
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Figure;IILcom/mascotcapsule/micro3d/v3/FigureLayout;Lcom/mascotcapsule/micro3d/v3/Effect3D;)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nRenderFigure
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nFlush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nFlush
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nRelease
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nRelease
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Graphics3D
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Graphics3D_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
