/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Effect3D */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Effect3D
#define _Included_com_mascotcapsule_micro3d_v3_Effect3D
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mascotcapsule_micro3d_v3_Effect3D_NORMAL_SHADING
#define com_mascotcapsule_micro3d_v3_Effect3D_NORMAL_SHADING 0L
#undef com_mascotcapsule_micro3d_v3_Effect3D_TOON_SHADING
#define com_mascotcapsule_micro3d_v3_Effect3D_TOON_SHADING 1L
/*
 * Class:     com_mascotcapsule_micro3d_v3_Effect3D
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Effect3D_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
