/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Light */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Light
#define _Included_com_mascotcapsule_micro3d_v3_Light
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_Light
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Light_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
