/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Util3D */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Util3D
#define _Included_com_mascotcapsule_micro3d_v3_Util3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_Util3D
 * Method:    sqrt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Util3D_sqrt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Util3D
 * Method:    sin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Util3D_sin
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Util3D
 * Method:    cos
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Util3D_cos
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
