/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_Texture */

#ifndef _Included_com_mascotcapsule_micro3d_v3_Texture
#define _Included_com_mascotcapsule_micro3d_v3_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_Texture
 * Method:    nInit
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_mascotcapsule_micro3d_v3_Texture_nInit
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Texture
 * Method:    nFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Texture_nFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_Texture
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_Texture_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
