/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mascotcapsule_micro3d_v3_AffineTrans */

#ifndef _Included_com_mascotcapsule_micro3d_v3_AffineTrans
#define _Included_com_mascotcapsule_micro3d_v3_AffineTrans
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nTransform
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nTransform
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nMultiply
 * Signature: (Lcom/mascotcapsule/micro3d/v3/AffineTrans;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nMultiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nMultiply2
 * Signature: (Lcom/mascotcapsule/micro3d/v3/AffineTrans;Lcom/mascotcapsule/micro3d/v3/AffineTrans;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nMultiply2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetRotationX
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetRotationX
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetRotationY
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetRotationY
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetRotationZ
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetRotationZ
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetIdentity
  (JNIEnv *, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetRotationV
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;I)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetRotationV
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nSetViewTtans
 * Signature: (Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;Lcom/mascotcapsule/micro3d/v3/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nSetViewTtans
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mascotcapsule_micro3d_v3_AffineTrans
 * Method:    nInitClass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mascotcapsule_micro3d_v3_AffineTrans_nInitClass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
